# jmx4perl, j4psh, curl, REST with Jolokia

Since `hawtio-1.2-redhat-403`, only the curl agent is supported and supposed to perform a basic authentication against Fuse platform (https://issues.jboss.org/browse/ENTESB-2418).
So, all the other tools like jmx4perl, j4psh or httpie will not work as they will receive a error 403 from the hawtio web container.

A possible workaround described by Gregor is to pass as parameter the information required to emulate a coookie session.

````
http://curl.haxx.se/docs/http-cookies.html

$ curl --cookie-jar curlcookies.txt -X POST http://admin:admin@localhost:8181/hawtio/auth/login
{"credentials":[],"principals":[{"name":"admin","type":"org.apache.karaf.jaas.boot.principal.RolePrincipal"},{"name":"admin","type":"org.apache.karaf.jaas.boot.principal.UserPrincipal"}]}

This will store:

localhost	FALSE	/hawtio	FALSE	0	JSESSIONID	1o9sty81ng9o4h74zxlcvg2zu

in curlcookies.txt file. We can then use this file to send correct cookies back to server, thus participating in Java session:
$ curl -v --cookie curlcookies.txt -X GET http://localhost:8181/hawtio/jolokia
````
## `jmx4perl` Tool

The +jmx4Perl+ uses the  Jolokia agent which has been deployed within the JBoss Fuse server or +hawtio+ console. It plays the role of a proxy, which on one side communicates with the MBeanServer within
in the application server and transfers JMX related information via HTTP and JSON to the client (i.e. this module). Here are the instructions to be followed to use the +hawtio-embed+ project available
 here or a Jboss Fuse server instance.
 
## Prerequisite

* See doc here : http://jolokia.org/tutorial.html (Install Jmx4Perl and j4psh)

## Install jmx4perl

* Open a Unix terminal and start this command

  perl -MCPAN -e shell

* When cpan prompt appears, execute this intsruction to install jmx4perl

  install JMX::Jmx4Perl
  
  If you issues during test execution you can skip test processing using `force install CPAN_MODULE`
   
## Grab data

* Open 2 unix terminals and move to the project containing the hawtio embedded jetty server

  cd hawtio-embedded
  
* Start the +Hawtio+ embedded client
  
  mvn exec:java
      
* Try out jmx4perl to get all the mbeans with the list instruction

  jmx4perl http://localhost:9090/hawtio/jolokia list
  
* If the JBoss Fuse server 6.1 has been started in another unix terminal, we can also query it as demonstrated with the 2 next requests.

NOTE : As Fuse 6.2 will support RBAC, it is most probable that requests proposed here will not work

** To list all the mbeans
  
  jmx4perl http://admin:admin@localhost:8181/hawtio/jolokia list
  
** To get info of a specific attribute of a mbean
  
  jmx4perl http://admin:admin@localhost:8181/hawtio/jolokia read java.lang:type=Runtime SpecVersion
  1.7

## j4psh shell command

The +j4psh+ jolokia perl tool is installed with +jmx4perl+ and provides a JMX command line shell to connect to a JMX server and next to navigate within the tree using
+cd+ instruction or +ls+ to list the mbeans defined at a specific level. To get the information of an attribute, you can use the +cat+ instruction. 
A https://www.youtube.com/watch?v=y9TuGzxD2To[demo has been recorded by Roland Huss] and explains how tou can navigate within the mbeans to get the information or execute an operation.

* Open 2 terminals

  cd hawtio-embedded

* Start the embedded client

  mvn exec:java

* Run j4psh commands to fetch data from the jolokia agent

  connect http://localhost:9090/hawtio/jolokia
    
WARNING: Due to a faulty reg expression, we can't connect to the Fuse server as it requires to pass a user:password within the http request. This PR should fix it - https://github.com/rhuss/jmx4perl/pull/47    
When the PR will be applied, than we will be able to use this connect string http request

  connect http://admin:admin@localhost:8181/hawtio/jolokia

Another possibility is to configure the .j4p config file to add a server definition as such :

You only need to add a Server into your default ~/.j4p configuration, e.g.

[source]
----
<Server fuse>
  Url  http://localhost:8181
  User admin
  Password s!cr!t
</Server>
----

Doc about server :  http://search.cpan.org/~roland/jmx4perl/scripts/check_jmx4perl#<Server>

You then can connect in j4psh with a simple "connect fuse".

The password can be even http://search.cpan.org/~roland/jmx4perl/scripts/jmx4perl#encrypt[encrypted].  

* When we are connected to the server, we can navigate within the tree and fetch the data or execute some operations
* Get HeapMemoryUsage attribute

    ls
    cd java.lang
    cd type=Memory
    cat HeapMemoryUsage

* Get Camel info

    cd ..
    cd org.apache.camel
    ls

* Change to the route1 Mbean & get attribute ExchangeCompleted

    cd context=camel-1,name="route1",type=routes
    cat ExchangesCompleted

*  Execute operation to get Stats of a Camel route

    exec dumpStatsAsXml(boolean) true
    Return: <stats exchangesCompleted="61" exchangesFailed="0" failuresHandled="0" redeliveries="0" externalRedeliveries="0"
             minProcessingTime="0" maxProcessingTime="6" totalProcessingTime="67" lastProcessingTime="1" deltaProcessingTime="0"
             meanProcessingTime="1" resetTimestamp="2014-09-12T20:45:06.191+0200" firstExchangeCompletedTimestamp="2014-09-12T20:45:07.218+0200"
             firstExchangeCompletedExchangeId="ID-Dabou-local-60864-1410547505770-0-2" firstExchangeFailureTimestamp=""
             firstExchangeFailureExchangeId="" lastExchangeCompletedTimestamp="2014-09-12T20:55:07.238+0200"
             lastExchangeCompletedExchangeId="ID-Dabou-local-60864-1410547505770-0-122" lastExchangeFailureTimestamp="" lastExchangeFailureExchangeId=""/>

## REST Curl requests

* Read +all mbeans+ info and save the JSON result into a file 

  curl -i http://admin:admin@localhost:8181/hawtio/jolokia/list > result.json            

## REST HTTPie requests

Instead of using the jmx4perl or j4psh jolokia tools, we can also fetch data from the jokokia bridge servlet using REST requests.
The syntax of the REST Jolokia requests is described https://jolokia.org/reference/html/protocol.html[here].
The following requests have been executed within a unix terminal using the https://github.com/jakubroztocil/httpie[`httpie tool`]

* Read +all mbeans+ info and save the JSON result into a file 
    
  http --pretty=all http://admin:admin@localhost:8181/hawtio/jolokia/list > result.json

* Mbean +java.lang+

** READ attribute

    http --pretty=all http://admin:admin@localhost:8181/hawtio/jolokia/read/java.lang:type=Memory/HeapMemoryUsage/used
    
** EXEC an operation    

    http --pretty=all http://admin:admin@localhost:8181/hawtio/jolokia/exec/java.lang:type=Memory/gc

* Mbean +org.apache.camel+

WARN : Add backslash before double quoted text

** READ ExchangesCompleted of a Camel Route ("route3") defined for the CamelContext (camel-demo-blueprint.xml)

    http --pretty=all http://admin:admin@localhost:8181/hawtio/jolokia/read/org.apache.camel:context=camel-demo-blueprint.xml,name=\"route3\",type=routes/ExchangesCompleted/
    HTTP/1.1 200 OK
    Access-Control-Allow-Origin: *
    Cache-Control: no-cache
    Content-Length: 194
    Content-Type: text/plain;charset=UTF-8
    Date: Thu, 30 Apr 2015 08:58:06 GMT
    Expires: Thu, 30 Apr 2015 07:58:06 GMT
    Pragma: no-cache
    Server: Jetty(8.1.14.v20131031)
    
    {"timestamp":1430384286,"status":200,"request":{"mbean":"org.apache.camel:context=camel-demo-blueprint.xml,name=\"route3\",type=routes","attribute":"ExchangesCompleted","type":"read"},"value":0}

** Execute the dumpStatsAsXml operation and setting the boolean value to true

    http http://admin:admin@localhost:8181/hawtio/jolokia/exec/org.apache.camel:context=camel-demo-blueprint.xml,name=\"route3\",type=routes/dumpStatsAsXml\(boolean\)/true
    HTTP/1.1 200 OK
    Access-Control-Allow-Origin: *
    Cache-Control: no-cache
    Content-Length: 967
    Content-Type: text/plain;charset=UTF-8
    Date: Thu, 30 Apr 2015 09:16:30 GMT
    Expires: Thu, 30 Apr 2015 08:16:30 GMT
    Pragma: no-cache
    Server: Jetty(8.1.14.v20131031)

    {"timestamp":1430385390,"status":200,"request":{"operation":"dumpStatsAsXml(boolean)","mbean":"org.apache.camel:context=camel-demo-blueprint.xml,name=\"route3\",type=routes","arguments":["true"],"type":"exec"},"value":"<stats exchangesCompleted=\"0\" exchangesFailed=\"426\" failuresHandled=\"0\" redeliveries=\"0\" externalRedeliveries=\"0\" minProcessingTime=\"0\" maxProcessingTime=\"0\" totalProcessingTime=\"0\" lastProcessingTime=\"0\" deltaProcessingTime=\"0\" meanProcessingTime=\"0\" resetTimestamp=\"2015-04-30T10:41:00.577+0200\" firstExchangeCompletedTimestamp=\"\" firstExchangeCompletedExchangeId=\"\" firstExchangeFailureTimestamp=\"2015-04-30T10:41:01.594+0200\" firstExchangeFailureExchangeId=\"ID-dabou-local-49325-1430383026073-1-2\" lastExchangeCompletedTimestamp=\"\" lastExchangeCompletedExchangeId=\"\" lastExchangeFailureTimestamp=\"2015-04-30T11:16:27.838+0200\" lastExchangeFailureExchangeId=\"ID-dabou-local-49325-1430383026073-1-852\"\/>"}
