:toc: macro

toc::[]

# jmx4perl, j4psh, curl, REST with Jolokia

Since `hawtio-1.2-redhat-403`, only the curl agent is supported and supposed to perform a basic authentication against Fuse platform 6.2 (https://issues.jboss.org/browse/ENTESB-2418).
So, all the other tools like jmx4perl, j4psh or httpie will not work as they will receive a error 403 from the hawtio web container.

A possible workaround described by Gregor is to pass as parameter the information required to emulate a coookie session.

----
http://curl.haxx.se/docs/http-cookies.html

$ curl --cookie-jar curlcookies.txt -X POST http://admin:admin@localhost:8181/hawtio/auth/login --data @credentials.json

where credentials.json contains the json roles, ...

{"credentials":[],"principals":[{"name":"admin","type":"org.apache.karaf.jaas.boot.principal.RolePrincipal"},{"name":"admin","type":"org.apache.karaf.jaas.boot.principal.UserPrincipal"}]}

Then, if the authentication succeeds you will ge a curlcookies.txt file containing the following information

# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

localhost    FALSE    /hawtio    FALSE    0    JSESSIONID    13fiw6kzz8fdn9h2oqd72qwfe

And now we can query jolokia

$ curl -v --cookie curlcookies.txt -X GET http://localhost:8181/hawtio/jolokia
*   Trying ::1...
* Connected to localhost (::1) port 8181 (#0)
> GET /hawtio/jolokia HTTP/1.1
> Host: localhost:8181
> User-Agent: curl/7.42.1
> Accept: */*
> Cookie: JSESSIONID=13fiw6kzz8fdn9h2oqd72qwfe
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< X-Frame-Options: SAMEORIGIN
----

or to specify for httpie that we are using the curl agent `User-Agent:curl`

## `jmx4perl` Tool

The +jmx4Perl+ uses the  Jolokia agent which has been deployed within the JBoss Fuse server or +hawtio+ console. It plays the role of a proxy, which on one side communicates with the MBeanServer within
in the application server and transfers JMX related information via HTTP and JSON to the client (i.e. this module). Here are the instructions to be followed to use the +hawtio-embed+ project available
 here or a Jboss Fuse server instance.
 
### Prerequisite

* See doc here : http://jolokia.org/tutorial.html (Install Jmx4Perl and j4psh)

### Install jmx4perl

* Open a Unix terminal and start this command

  perl -MCPAN -e shell

* When cpan prompt appears, execute this intsruction to install jmx4perl

  install JMX::Jmx4Perl
  
  If you issues during test execution you can skip test processing using `force install CPAN_MODULE`
   
### Grab data

* Open 2 unix terminals and move to the project containing the hawtio embedded jetty server

  cd hawtio-embedded
  
* Start the +Hawtio+ embedded client
  
  mvn exec:java
      
* Try out jmx4perl to get all the mbeans with the list instruction

  jmx4perl http://localhost:9090/hawtio/jolokia list
  
* If the JBoss Fuse server 6.1 has been started in another unix terminal, we can also query it as demonstrated with the 2 next requests.

NOTE : As Fuse 6.2 will support RBAC, it is most probable that requests proposed here will not work

** To list all the mbeans
  
  jmx4perl http://admin:admin@localhost:8181/hawtio/jolokia list
  
** To get info of a specific attribute of a mbean
  
  jmx4perl http://admin:admin@localhost:8181/hawtio/jolokia read java.lang:type=Runtime SpecVersion
  1.7

## j4psh shell command

The +j4psh+ jolokia perl tool is installed with +jmx4perl+ and provides a JMX command line shell to connect to a JMX server and next to navigate within the tree using
+cd+ instruction or +ls+ to list the mbeans defined at a specific level. To get the information of an attribute, you can use the +cat+ instruction. 
A https://www.youtube.com/watch?v=y9TuGzxD2To[demo has been recorded by Roland Huss] and explains how tou can navigate within the mbeans to get the information or execute an operation.

* Open 2 terminals

  cd hawtio-embedded

* Start the embedded client

  mvn exec:java

* Run j4psh commands to fetch data from the jolokia agent

  connect http://localhost:9090/hawtio/jolokia
    
WARNING: Due to a faulty reg expression, we can't connect to the Fuse server as it requires to pass a user:password within the http request. This PR should fix it - https://github.com/rhuss/jmx4perl/pull/47    
When the PR will be applied, than we will be able to use this connect string http request

  connect http://admin:admin@localhost:8181/hawtio/jolokia

Another possibility is to configure the .j4p config file to add a server definition as such :

You only need to add a Server into your default ~/.j4p configuration, e.g.

[source]
----
<Server fuse>
  Url  http://localhost:8181
  User admin
  Password s!cr!t
</Server>
----

Doc about server :  http://search.cpan.org/~roland/jmx4perl/scripts/check_jmx4perl#<Server>

You then can connect in j4psh with a simple "connect fuse".

The password can be even http://search.cpan.org/~roland/jmx4perl/scripts/jmx4perl#encrypt[encrypted].  

* When we are connected to the server, we can navigate within the tree and fetch the data or execute some operations
* Get HeapMemoryUsage attribute

    ls
    cd java.lang
    cd type=Memory
    cat HeapMemoryUsage

* Get Camel info

    cd ..
    cd org.apache.camel
    ls

* Change to the route1 Mbean & get attribute ExchangeCompleted

    cd context=camel-1,name="route1",type=routes
    cat ExchangesCompleted

*  Execute operation to get Stats of a Camel route

    exec dumpStatsAsXml(boolean) true
    Return: <stats exchangesCompleted="61" exchangesFailed="0" failuresHandled="0" redeliveries="0" externalRedeliveries="0"
             minProcessingTime="0" maxProcessingTime="6" totalProcessingTime="67" lastProcessingTime="1" deltaProcessingTime="0"
             meanProcessingTime="1" resetTimestamp="2014-09-12T20:45:06.191+0200" firstExchangeCompletedTimestamp="2014-09-12T20:45:07.218+0200"
             firstExchangeCompletedExchangeId="ID-Dabou-local-60864-1410547505770-0-2" firstExchangeFailureTimestamp=""
             firstExchangeFailureExchangeId="" lastExchangeCompletedTimestamp="2014-09-12T20:55:07.238+0200"
             lastExchangeCompletedExchangeId="ID-Dabou-local-60864-1410547505770-0-122" lastExchangeFailureTimestamp="" lastExchangeFailureExchangeId=""/>

## REST Curl requests

* Read +all mbeans+ info and save the JSON result into a file 

  curl -i http://admin:admin@localhost:8181/hawtio/jolokia/list > result.json            

## HTTPie requests

Instead of using the jmx4perl or j4psh jolokia tools, we can also fetch data from the jokokia bridge servlet using REST requests.
The syntax of the REST Jolokia requests is described https://jolokia.org/reference/html/protocol.html[here].
The following requests have been executed within a unix terminal using the https://github.com/jakubroztocil/httpie[`httpie tool`]

* Read +all mbeans+ info and save the JSON result into a file 
    
  http --pretty=all http://admin:admin@localhost:8181/hawtio/jolokia/list > result.json

* Mbean +java.lang+

** READ attribute

    http --pretty=all http://admin:admin@localhost:8181/hawtio/jolokia/read/java.lang:type=Memory/HeapMemoryUsage/used
    
** EXEC an operation    

    http --pretty=all http://admin:admin@localhost:8181/hawtio/jolokia/exec/java.lang:type=Memory/gc

* Mbean +org.apache.camel+

WARN : Add backslash before double quoted text

** READ ExchangesCompleted of a Camel Route ("route3") defined for the CamelContext (camel-demo-blueprint.xml)

    http --pretty=all http://admin:admin@localhost:8181/hawtio/jolokia/read/org.apache.camel:context=camel-demo-blueprint.xml,name=\"route3\",type=routes/ExchangesCompleted/
    HTTP/1.1 200 OK
    Access-Control-Allow-Origin: *
    Cache-Control: no-cache
    Content-Length: 194
    Content-Type: text/plain;charset=UTF-8
    Date: Thu, 30 Apr 2015 08:58:06 GMT
    Expires: Thu, 30 Apr 2015 07:58:06 GMT
    Pragma: no-cache
    Server: Jetty(8.1.14.v20131031)
    
    {"timestamp":1430384286,"status":200,"request":{"mbean":"org.apache.camel:context=camel-demo-blueprint.xml,name=\"route3\",type=routes","attribute":"ExchangesCompleted","type":"read"},"value":0}

** Execute the dumpStatsAsXml operation and setting the boolean value to true

    http http://admin:admin@localhost:8181/hawtio/jolokia/exec/org.apache.camel:context=camel-demo-blueprint.xml,name=\"route3\",type=routes/dumpStatsAsXml\(boolean\)/true
    HTTP/1.1 200 OK
    Access-Control-Allow-Origin: *
    Cache-Control: no-cache
    Content-Length: 967
    Content-Type: text/plain;charset=UTF-8
    Date: Thu, 30 Apr 2015 09:16:30 GMT
    Expires: Thu, 30 Apr 2015 08:16:30 GMT
    Pragma: no-cache
    Server: Jetty(8.1.14.v20131031)

    {"timestamp":1430385390,"status":200,"request":{"operation":"dumpStatsAsXml(boolean)","mbean":"org.apache.camel:context=camel-demo-blueprint.xml,name=\"route3\",type=routes","arguments":["true"],"type":"exec"},"value":"<stats exchangesCompleted=\"0\" exchangesFailed=\"426\" failuresHandled=\"0\" redeliveries=\"0\" externalRedeliveries=\"0\" minProcessingTime=\"0\" maxProcessingTime=\"0\" totalProcessingTime=\"0\" lastProcessingTime=\"0\" deltaProcessingTime=\"0\" meanProcessingTime=\"0\" resetTimestamp=\"2015-04-30T10:41:00.577+0200\" firstExchangeCompletedTimestamp=\"\" firstExchangeCompletedExchangeId=\"\" firstExchangeFailureTimestamp=\"2015-04-30T10:41:01.594+0200\" firstExchangeFailureExchangeId=\"ID-dabou-local-49325-1430383026073-1-2\" lastExchangeCompletedTimestamp=\"\" lastExchangeCompletedExchangeId=\"\" lastExchangeFailureTimestamp=\"2015-04-30T11:16:27.838+0200\" lastExchangeFailureExchangeId=\"ID-dabou-local-49325-1430383026073-1-852\"\/>"}

Since Fuse 6.2, the basic authentication is not longer supported excepted for the User-agent: curl as we have explained earlier. To figure out this issue, we can setup a cookie session and reuse the session for 
next requests

    http --session=admin -a admin:admin -f POST http://localhost:8181/hawtio/auth/login
    HTTP/1.1 200 OK
    Access-Control-Allow-Origin: *
    Cache-Control: max-age=0, no-cache, must-revalidate, proxy-revalidate, private
    Content-Type: application/json;charset=ISO-8859-1
    Expires: Thu, 01 Jan 1970 00:00:00 GMT
    Pragma: no-cache
    Server: Jetty(8.1.16.v20140903)
    Set-Cookie: JSESSIONID=126a0ukbkhjyj15t39pq9zy6lc;Path=/hawtio;HttpOnly
    Transfer-Encoding: chunked
    X-Frame-Options: SAMEORIGIN
     
    {
        "credentials": [],
        "principals": [
            {
                "name": "Auditor",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "manager",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "Maintainer",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "Monitor",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "Administrator",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "admin",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "admin",
                "type": "org.apache.karaf.jaas.boot.principal.UserPrincipal"
            },
            {
                "name": "Operator",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "SuperUser",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "Deployer",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            },
            {
                "name": "viewer",
                "type": "org.apache.karaf.jaas.boot.principal.RolePrincipal"
            }
        ]
    }

    http --session=admin http://localhost:8181/hawtio/jolokia/list
    
    HTTP/1.1 200 OK
    Access-Control-Allow-Origin: *
    Cache-Control: no-cache
    Content-Type: text/plain;charset=UTF-8
    Date: Mon, 04 May 2015 12:02:46 GMT
    Expires: Mon, 04 May 2015 11:02:46 GMT
    Pragma: no-cache
    Server: Jetty(8.1.16.v20140903)
    Transfer-Encoding: chunked
    X-Frame-Options: SAMEORIGIN
     
    {"timestamp":1430740966,"status":200,"request":{"type":"list"},"value":{"JMImplementation":{"type=MBeanServerDelegate":{"desc":"Represents  the MBean server from the management point of view.","attr":{"ImplementationVendor":{"desc":"the JMX implementation vendor (the vendor of ...
    
    http --session=admin http://localhost:8181/hawtio/jolokia/version
    
    http --session=admin http://localhost:8181/hawtio/jolokia/search/java.lang:*
    {"timestamp":1430741751,"status":200,"request":{"mbean":"java.lang:*","type":"search"},"value":["java.lang:type=Compilation","java.lang:type=Memory","java.lang:name=PS Eden Space,type=MemoryPool","java.lang:name=PS Survivor Space,type=MemoryPool","java.lang:name=Code Cache,type=MemoryPool","java.lang:name=PS MarkSweep,type=GarbageCollector","java.lang:type=Runtime","java.lang:name=PS Perm Gen,type=MemoryPool","java.lang:type=ClassLoading","java.lang:name=PS Scavenge,type=GarbageCollector","java.lang:type=OperatingSystem","java.lang:type=Threading","java.lang:name=PS Old Gen,type=MemoryPool","java.lang:name=CodeCacheManager,type=MemoryManager"]}
    
    http --session=admin http://localhost:8181/hawtio/jolokia/list/java.lang/type=Memory
    {"timestamp":1430741842,"status":200,"request":{"path":"java.lang\/type=Memory","type":"list"},"value":{"desc":"Information on the management interface of the MBean","op":{"gc":{"ret":"void","desc":"gc","args":[]}},"attr":{"Verbose":{"desc":"Verbose","type":"boolean","rw":true},"ObjectPendingFinalizationCount":{"desc":"ObjectPendingFinalizationCount","type":"int","rw":false},"NonHeapMemoryUsage":{"desc":"NonHeapMemoryUsage","type":"javax.management.openmbean.CompositeData","rw":false},"HeapMemoryUsage":{"desc":"HeapMemoryUsage","type":"javax.management.openmbean.CompositeData","rw":false},"ObjectName":{"desc":"ObjectName","type":"javax.management.ObjectName","rw":false}}}}

## Httpie Search

Domain : io.fabric8, Type : type=ProfileManagement

* Get attributes

----
http --session=admin -a admin:admin http://localhost:8181/hawtio/jolokia/list/io.fabric8/type=ProfileManagement/attr

{"timestamp":1430811390,"status":200,"request":{"path":"io.fabric8\/type=ProfileManagement\/attr","type":"list"},"value":{"Versions":{"desc":"Versions","type":"[Ljava.lang.String;","rw":false}}}
----

* Get operations

----
http --session=admin -a admin:admin http://localhost:8181/hawtio/jolokia/list/io.fabric8/type=ProfileManagement/op

{"timestamp":1430811396,"status":200,"request":{"path":"io.fabric8\/type=ProfileManagement\/op","type":"list"},"value":{"getVersion":{"ret":"javax.management.openmbean.CompositeData","desc":"getVersion","args":[{"desc":"p0","name":"p0","type":"java.lang.String"}]},"deleteVersion":{"ret":"void","desc":"deleteVersion","args":[{"desc":"p0","name":"p0","type":"java.lang.String"}]},"deleteProfile":{"ret":"void","desc":"deleteProfile","args":[{"desc":"p0","name":"p0","type":"java.lang.String"},{"desc":"p1","name":"p1","type":"java.lang.String"},{"desc":"p2","name":"p2","type":"boolean"}]},"createVersion":{"ret":"javax.management.openmbean.CompositeData","desc":"createVersion","args":[{"desc":"p0","name":"p0","type":"javax.management.openmbean.CompositeData"}]},"updateProfile":{"ret":"javax.management.openmbean.CompositeData","desc":"updateProfile","args":[{"desc":"p0","name":"p0","type":"javax.management.openmbean.CompositeData"}]},"getProfile":{"ret":"javax.management.openmbean.CompositeData","desc":"getProfile","args":[{"desc":"p0","name":"p0","type":"java.lang.String"},{"desc":"p1","name":"p1","type":"java.lang.String"}]},"createProfile":{"ret":"javax.management.openmbean.CompositeData","desc":"createProfile","args":[{"desc":"p0","name":"p0","type":"javax.management.openmbean.CompositeData"}]},"createVersionFrom":{"ret":"javax.management.openmbean.CompositeData","desc":"createVersionFrom","args":[{"desc":"p0","name":"p0","type":"java.lang.String"},{"desc":"p1","name":"p1","type":"java.lang.String"},{"desc":"p2","name":"p2","type":"javax.management.openmbean.TabularData"}]}}}
----

## Enable Debug option of Jolokia

Jolokia proposes a Config mbean where we can change the Debug boolean value (true/false). When the debugger is switched to on, then we can call the +debugInfo+ operation to collect the responses
returned by jolokia

----
http --session=admin http://localhost:8181/hawtio/jolokia/write/jolokia:type=Config/Debug/true
http --session=admin http://localhost:8181/hawtio/jolokia/read/jolokia:type=Config

http --session=admin http://localhost:8181/hawtio/jolokia/exec/jolokia:type=Config/debugInfo
----

Example using jolokia-osgi 1.2.3 deployed Apache Karaf 2.3.11

----
http http://localhost:8181/jolokia/write/jolokia:type=Config/Debug/true

{"timestamp":1430831827,"status":200,"request":{"mbean":"jolokia:type=Config","value":"true","attribute":"Debug","type":"write"},"value":false}

http http://localhost:8181/jolokia/read/jolokia:type=Config

{"timestamp":1430831832,"status":200,"request":{"mbean":"jolokia:type=Config","type":"read"},"value":{"HistoryMaxEntries":10,"Debug":true,"MaxDebugEntries":100,"HistorySize":82}}

http http://localhost:8181/jolokia/exec/jolokia:type=Config/debugInfo

{"timestamp":1430831836,"status":200,"request":{"operation":"debugInfo","mbean":"jolokia:type=Config","type":"exec"},"value":"1430831832: Execution time: 1 ms\n1430831832: Response: {\"timestamp\":1430831832,\"status\":200,\"request\":{\"mbean\":\"jolokia:type=Config\",\"type\":\"read\"},\"value\":{\"HistoryMaxEntries\":10,\"Debug\":true,\"MaxDebugEntries\":100,\"HistorySize\":82}}\n"}
----

## Send a Post request to jolokia

The syntax of the POST requests is defined https://jolokia.org/reference/html/protocol.html#post-request[here]

----
http POST http://localhost:8181/jolokia  < jol-req1.json
----

where the json request looks like 

----
{
    "type" : "read",
    "mbean" : "java.lang:type=Memory",
    "attribute" : "HeapMemoryUsage",
    "path" : "used",
  }
----